#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Scannercheck.Resource", IsApplication=true)]

namespace Scannercheck
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Scannercheck.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Scannercheck.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Scannercheck.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000b
			public const int aqua = 2130968587;
			
			// aapt resource value: 0x7f040011
			public const int black = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int blue = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int dark_grey = 2130968594;
			
			// aapt resource value: 0x7f040004
			public const int fuchsia = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int green = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int grey = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int lime = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int maroon = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int navy = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int olive = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int purple = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int red = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int silver = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int teal = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int theme_blue = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int theme_green = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int white = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int yellow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_assignment_ind_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_dashboard_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_history_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_home_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_scan = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_scan_bottom = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_scan_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int image = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int bottomtoolbarmain = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int button = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int container = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int content = 2131165189;
			
			// aapt resource value: 0x7f07001a
			public const int contentFrame = 2131165210;
			
			// aapt resource value: 0x7f07000d
			public const int footer = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int footer_border = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int header = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int header_menu_left = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int imageView = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int main_content = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int scanbutton = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int searchView1 = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int tab1 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int tab1_icon = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int tab1_text = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int tab2 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int tab2_icon = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int tab2_text = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int tab3 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int tab3_icon = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int tab3_text = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int tab4 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int tab4_icon = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int tab4_text = 2131165209;
			
			// aapt resource value: 0x7f070009
			public const int textView = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int textView2 = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscanneractivitylayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscannerfragmentlayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int description = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int title = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
